version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
